language: python
python:
  # - 3.4
  - 3.5
  - 3.6
  - "3.7-dev"
  - "pypy3.5"
install:
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - python -m unittest discover
notifications:
  email: false
